---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "elixir template"
labels:
  template: "elixir-template"
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: elixir
    spec:
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
      selector:
        matchLabels:
          app: elixir
      template:
        metadata:
          labels:
            app: elixir
        spec:
          containers:
            - image: europe-north1-docker.pkg.dev/elixir-337919/antimon-docker/weber:$(VERSION)
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                # upper limit that container can acquire even if node has plenty of resources
                limits:
                  cpu: 200m
                  memory: 2560Mi
              name: elixir
              ports:
                - containerPort: 4000
              readinessProbe:
                httpGet:
                  path: /ping
                  port: 4000
              livenessProbe:
                httpGet:
                  path: /ping
                  port: 4000
                initialDelaySeconds: 100
parameters:
  - name: "VERSION"
    description: "version"
    value: "1"