name: Elixir test project

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request_target:
    branches:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.ANTI_GCP_PROJECT_ID }}

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  compile:
    name: Compile, Package and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/348769354616/locations/global/workloadIdentityPools/antimon-pool/providers/antimon-provider'
          service_account: 'artifactregistryt@${{ env.PROJECT_ID }}.iam.gserviceaccount.com '

      - name: Compile
        run: |
          docker build  -f docker/Dockerfile -t weber:latest .
          docker tag weber:latest "europe-north1-docker.pkg.dev/${PROJECT_ID}/antimon-docker/weber:${GITHUB_SHA}"
          docker push "europe-north1-docker.pkg.dev/${PROJECT_ID}/antimon-docker/weber:${GITHUB_SHA}"
